import { Router } from 'express';
import { throttlingMiddleware } from '../../middlewares/throttlingMiddleware.js';
import { authRateLimit, apiRateLimit, dataRateLimit } from '../../middlewares/rateLimitMiddleware.js';
import searchRoutes from '../searchRoutes.js';
import employeeRoutes from '../employeeRoutes.js';
import paymentRoutes from '../paymentRoutes.js';
import authRoutes from '../authRoutes.js';
import assetRoutes from '../assetRoutes.js';
import throttlingRoutes from '../throttlingRoutes.js';
import payrollBonusRoutes from '../payrollBonusRoutes.js';
import payrollAuditRoutes from '../payrollAuditRoutes.js';
import auditRoutes from '../auditRoutes.js';
import balanceRoutes from '../balanceRoutes.js';
import trustlineRoutes from '../trustlineRoutes.js';
import payrollRoutes from '../payroll.routes.js';
import exportRoutes from '../exportRoutes.js';
import taxRoutes from '../taxRoutes.js';
import multiSigRoutes from '../multiSigRoutes.js';
import rateLimitRoutes from '../rateLimitRoutes.js';
import freezeRoutes from '../freezeRoutes.js';
import contractUpgradeRoutes from '../contractUpgradeRoutes.js';
import forecastRoutes from '../forecastRoutes.js';
import benefitsRoutes from '../benefitsRoutes.js';
import scheduleRoutes from '../scheduleRoutes.js';
import contractEventRoutes from '../contractEventRoutes.js';
import certificateRoutes from '../certificateRoutes.js';
import cashFlowForecastRoutes from '../cashFlowForecastRoutes.js';
import adminRoutes from '../adminRoutes.js';
import tenantUsageRoutes from '../tenantUsageRoutes.js';
import auditAnalyticsRoutes from '../auditAnalyticsRoutes.js';
import smartRateLimitRoutes from '../smartRateLimitRoutes.js';
import tenantSecurityRoutes from '../tenantSecurityRoutes.js';

const router = Router();

router.use('/auth', authRateLimit(), authRoutes);
router.use('/search', dataRateLimit(), searchRoutes);
router.use('/employees', dataRateLimit(), employeeRoutes);
router.use('/payments', apiRateLimit(), throttlingMiddleware(), paymentRoutes);
router.use('/assets', dataRateLimit(), assetRoutes);
router.use('/throttling', apiRateLimit(), throttlingRoutes);
router.use('/payroll-bonus', apiRateLimit(), payrollBonusRoutes);
router.use('/payroll/audit', dataRateLimit(), payrollAuditRoutes);
router.use('/payroll', dataRateLimit(), payrollRoutes);
router.use('/audit', dataRateLimit(), auditRoutes);
router.use('/balance', dataRateLimit(), balanceRoutes);
router.use('/trustline', dataRateLimit(), trustlineRoutes);
router.use('/exports', dataRateLimit(), exportRoutes);
router.use('/taxes', dataRateLimit(), taxRoutes);
router.use('/forecast', dataRateLimit(), forecastRoutes);
router.use('/multisig', apiRateLimit(), multiSigRoutes);
router.use('/rate-limit', apiRateLimit(), rateLimitRoutes);
router.use('/freeze', apiRateLimit(), freezeRoutes);
router.use('/contracts', apiRateLimit(), contractUpgradeRoutes);
router.use('/benefits', dataRateLimit(), benefitsRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/events', contractEventRoutes);
router.use('/certificates', certificateRoutes);
router.use('/cash-flow', cashFlowForecastRoutes);
router.use('/admin', adminRoutes);
router.use('/usage', tenantUsageRoutes);
router.use('/audit-analytics', auditAnalyticsRoutes);
router.use('/smart-rate-limit', smartRateLimitRoutes);
router.use('/tenant-security', tenantSecurityRoutes);

export default router;
